// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class chrefefergvrehrehjcmrge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chrefefergvrehrehjcmrge));
        
        string IMigrationMetadata.Id
        {
            get { return "201905171205079_chrefefergvrehrehjcmrge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
